#+title: =The Owl Dotfiles=
#+AUTHOR: Matheus Almeida

* About this Dotfiles

This is the personal configuration of a lonely owl, seeking the truth following the path of The Great Debugger God.
If you have any suggestion fell free to open a Issue or send me a message on [[https://twitter.com/Math_Almeid][Twitter]]

* Usage

For use ou dotfiles you can run the symlink script or run just emacs in isolation mode for testing purposes.

** Owl Mode

To install all dependencies and install the entire system just run the build script for your distro.

This script will: 
 
- Configure dotfiles path moving the project and creating the required folders
- Configure Emacs and his dependencies
- Configure ZSH and his dependencies
- Configure asdf

*** Debian

#+begin_src sh

make deb-build

#+end_src

*** Arch

#+begin_src sh

make arch-build

#+end_src

** Isolation Mode

I made a isolation mode if you want to test Olw Emacs before install it. For use this mode just use the =isolation-setup= and the sh script.

*** Debian

#+begin_src emacs-lisp

make deb-isolation-setup && sh ~/Workspaces/Personal/dotfiles/Emacs/isolation/run-emacs.sh

#+end_src

*** Arch

#+begin_src emacs-lisp

make arch-isolation-setup && sh ~/Workspaces/Personal/dotfiles/Emacs/isolation/run-emacs.sh

#+end_src
