#+title: =The Owl Dotfiles=
#+AUTHOR: Matheus Almeida

* About this Dotfiles

This is the personal configuration of a lonely owl, seeking the truth following the path of The Great Debugger God.
If you have any suggestion fell free to open a Issue or send me a message on [[https://twitter.com/Math_Almeid][Twitter]]

* Usage

For use ou dotfiles you can run the symlink script or run just emacs in isolation mode for testing purposes.

** Owl Mode

To install all dependencies and install the entire system just run:

#+begin_src sh

make build

#+end_src

This script will: 
 
- Configure dotfiles path moving the project and creating the required folders
- Configure Emacs and his dependencies
- Configure ZSH and his dependencies
- Configure asdf and Ruby in the latest version

** Isolation Mode

I made a isolation mode if you want to test Olw Emacs before install it, for use in this mode just run the script in isolation folder.

#+begin_src emacs-lisp

sh Workspaces/Personal/dotfiles/Emacs/isolation/run-emacs.sh

#+end_src

In this mode you need to install all the dependencies for your own.
I create a Makefile to help with this with these actions:

#+begin_src sh

zsh-dependencies # Install all zsh dependencies
symlink-dependencies # Install asdf and Ruby for symlinks
emacs-dependencies # Install all emacs dependencies

#+end_src

To run Isolation Mode you just need the =emacs-dependecies= action
