#+title: =The Owl Dotfiles=
#+AUTHOR: Matheus Almeida

* About this Dotfiles

This is the personal configuration of a lonely owl, seeking the truth following the path of The Great Debugger God.
If you have any suggestion fell free to open a Issue or send me a message on [[https://twitter.com/Math_Almeid][Twitter]]

* Dependencies

This configuration requires some dependencies that need to be satisfied before the symlink is made

** Path

This configuration uses a specific path to work correctilly, I will made this dynamic in a near future.
The path is:

=~/Workspaces/Personal/dotfiles= 

** Zsh

This configuration uses Zsh as default shell.

*** Instalation

#+begin_src sh

sudo apt-get install zsh

#+end_src

*** Change default shell

#+begin_src sh

chsh -s $(which zsh)

#+end_src

** asdf

For runtime management we use [[https://github.com/asdf-vm/asdf][asdf]]

*** Debian

- Clone the  asdf Repo

#+begin_src sh

git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.11.3

#+end_src

- Install the dependencies

#+begin_src sh

sudo apt install build-essencial zlib1g-dev libyaml-dev libssl-dev

#+end_src

** Ruby

Ruby needs to be installed and configured for running the symlinks script.


#+begin_src sh

asdf plugin-add ruby && asdf install ruby latest && asdf global ruby latest

#+end_src

** Fonts

There's two fonts we need to install to be used in Emacs configuration

*** Debian

#+begin_src sh

sudo apt install fonts-firacode fonts-cantarell

#+end_src

** Search engine

We use [[https://github.com/ggreer/the_silver_searcher][The Silver Searcher]] as searching tool.

*** Debian 

#+begin_src sh

sudo apt install silversearcher-ag

#+end_src

* Usage

For use ou dotfiles you can run the symlink script or run just emacs in isolation mode for testing purposes.

** Owl Mode

Just run and all will be configured :D

#+begin_src sh

ruby symlinks.rb

#+end_src

** Isolation Mode

I made a isolation mode if you want to test Olw Emacs before install it, for use in this mode just run the script in isolation folder.

#+begin_src emacs-lisp

sh Workspaces/Personal/dotfiles/Emacs/isolation/run-emacs.sh

#+end_src
