#+title: =The Torresmo Dotfiles=
#+AUTHOR: Matheus Almeida

* About this Dotfiles

This is the personal configuration of Torresmo, seeking the truth following the path of The Great Debugger God.
If you have any suggestion fell free to open a Issue or send me a message on [[https://twitter.com/Math_Almeid][Twitter]]

* Usage

For use ou dotfiles you can run the symlink script or run just emacs in isolation mode for testing purposes.
=Don't forget to change .gitconfig file to your configuration!=

** Torresmo Mode

Configure the entire system, including the desktop configuration.

This script will: 
 
- Configure hyprland and graphical environment
- Configure dotfiles path moving the project and creating the required folders
- Configure Emacs and his dependencies
- Configure ZSH and his dependencies
- Configure asdf

#+begin_src sh

make build
  
#+end_src

** Portability Mode

Configure the terminal, editor, and configuration files for your distro by running the corresponding build script.

This script will: 
 
- Configure dotfiles path moving the project and creating the required folders
- Configure Emacs and his dependencies
- Configure ZSH and his dependencies
- Configure asdf

*** Debian based distros

#+begin_src sh

make deb-based

#+end_src

*** Arch based distros

#+begin_src sh

make arch-based

#+end_src

** Isolation Mode

I made a isolation mode if you want to test Torresmo Emacs before install it. For use this mode just use the =isolation-setup= and the sh script.

*** Debian

#+begin_src emacs-lisp

make deb-isolation-setup && sh ~/Workspaces/Personal/dotfiles/Emacs/isolation/run-emacs.sh

#+end_src

*** Arch

#+begin_src emacs-lisp

make arch-isolation-setup && sh ~/Workspaces/Personal/dotfiles/Emacs/isolation/run-emacs.sh

#+end_src
