general {
    disable_loading_bar = false
    hide_cursor = true
    grace = 0
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 5
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.26
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgba(6CB6D9aa)
    inner_color = rgba(1f1d2e80)
    font_color = rgb(e0def4)
    fade_on_empty = false
    placeholder_text = <i>Senha...</i>
    hide_input = false
    position = 0, 50
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H:%M")"
    color = rgba(e0def4, 1.0)
    font_size = 90
    font_family = Inter
    position = 0, 200
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%a, %B %e")"
    color = rgba(e0def4, 1.0)
    font_size = 24
    font_family = Inter
    position = 0, 100
    halign = center
    valign = center
}