#+title: =Owl Emacs configuration=
#+AUTHOR: Matheus Almeida
#+PROPERTY: header-args:emacs-lisp :tangle ./init.el :mkdirp yes

* About this configuration

This is the personal configuration of a lonely owl, seeking the truth following the path of The Great Debugger God.
If you have any suggestion fell free to open a Issue or send me a message on [[https://twitter.com/Math_Almeid][Twitter]]

* General Configuration

This section configures core things of this configuration.

** Startup Performace

#+begin_src emacs-lisp

  ;; This defines the number of bytes of consing between garbage collections. 
  ;; The default is 800 kilobytes.  Measured in bytes.
  (setq gc-cons-threshold (* 20 1000 1000))

  (defun owl/display-startup-time ()
    (message "Emacs loaded in %s with %d garbage collections."
             (format "%.2f seconds"
                     (float-time
                       (time-subtract after-init-time before-init-time)))
             gcs-done))

  (add-hook 'emacs-startup-hook #'owl/display-startup-time)

#+end_src

** Package System Setup

Use [[https://github.com/jwiegley/use-package][use-package]] to make easy to install and configure packages

#+begin_src emacs-lisp

  (require 'package)

  (setq package-archives '(("melpa" . "https://melpa.org/packages/")
                           ("org" . "https://orgmode.org/elpa/")
                           ("elpa" . "https://elpa.gnu.org/packages/")))

  (package-initialize)
  (unless package-archive-contents
    (package-refresh-contents))

  ;; initialize use-package on non-Linux platforms
  (unless (package-installed-p 'use-package)
    (package-install 'use-package))

  (require 'use-package)
  (setq use-package-always-ensure t)

#+end_src

** Keep Folders Clean

We use the [[https://github.com/emacscollective/no-littering/blob/master/no-littering.el][no-littering]] package to keep folders where we edit files and the Emacs configuration folder clean.

#+begin_src emacs-lisp

  ;; Change the user-emacs-directory to keep unwanted things out of ~/.emacs.d
  (setq user-emacs-directory "~/.cache/emacs")

  ;; Use no-littering to automatically set common paths to the new user-emacs-directory
  (use-package no-littering)

  ;; no-littering doesn't set this by default so we must place
  ;; auto save files in the same path as it uses for sessions
  (setq auto-save-file-name-transforms
        `((".*" ,(no-littering-expand-var-file-name "auto-save/") t)))

#+end_src

** Keybidings

*** Esc Cancels All

#+begin_src emacs-lisp

  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)

#+end_src

*** Yes/No Replacement

Replaces the words "yes" and "no" for "y" or "n"

#+begin_src emacs-lisp

  (defalias 'yes-or-no-p 'y-or-n-p) ;; replaces "yes or no" by "y or n"
  
#+end_src

*** Rebind C-u

Since I let =evil-mode= take over =C-u= for buffer scrolling, I need to re-bind the universal-argument command to another key sequence. I’m choosing =C-M-u= for this purpose.

#+begin_src emacs-lisp

  (global-set-key (kbd "C-M-u") 'universal-argument)

#+end_src

*** Simplify Leader Bidings

[[https://github.com/noctuid/general.el][general.el]] is a fantastic lib for defining prefixed keybidings, especially in conjunction with Evil modes.

#+begin_src emacs-lisp

  (use-package general
    :config
    (general-evil-setup t)

    (general-create-definer owl/leader-keys
      :keymaps '(normal insert visual emacs)
      :prefix "SPC" ;; Works on normal mode
      :global-prefix "C-SPC") ;; Works in all modes

    (owl/leader-keys
      "m" '(:ignore t :which-key "Misc")
      "c" '(:ignore t :which-key "Config")
      "mt" '(counsel-load-theme :which-key "choose theme")
      "cf" '(lambda () (interactive) (find-file (expand-file-name "~/Workspaces/Personal/dotfiles/Emacs/Emacs.org")))))

#+end_src

*** Stateful Keymas with Hydra

#+begin_src emacs-lisp

  (use-package hydra
    :defer t)

#+end_src

*** Let's Be Evil

Since I come from Vim, I like to use [[https://evil.readthedocs.io/en/latest/index.html][evil-mode.]]
The [[https://github.com/emacs-evil/evil-collection][evil-collection]] is used to automactically configure various Emacs modes with Vi-like keybindings for evil-mode

#+begin_src emacs-lisp

  (use-package undo-tree
    :init
    (global-undo-tree-mode 1))

  (use-package evil
    :init
    (setq evil-want-integration t)
    (setq evil-want-keybinding nil)
    (setq evil-want-C-u-scroll t)
    (setq evil-want-C-i-jump nil)
    (setq evil-respect-visual-line-mode t)
    (setq evil-undo-system 'undo-tree)
    :config
    (evil-mode 1)
    (define-key evil-insert-state-map (kbd "C-g") 'evil-normal-state)
    (define-key evil-insert-state-map (kbd "C-h") 'evil-delete-backward-char-and-join)

    ;; Use visual line motions even outside of visual-line-mode buffers
    (evil-global-set-key 'motion "j" 'evil-next-visual-line)
    (evil-global-set-key 'motion "k" 'evil-previous-visual-line)

    (evil-set-initial-state 'messages-buffer-mode 'normal)
    (evil-set-initial-state 'dashboard-mode 'normal))

  (use-package evil-collection
    :after evil
    :config
    (evil-collection-init))

#+end_src

*** Files and Buffers Keybidings

Create keybidings for find files and buffers

#+begin_src emacs-lisp

  (owl/leader-keys 
    "f" '(:ignore t :which-key "File")
    "b" '(:ignore t :which-key "Buffer")
    "ff" '(counsel-find-file :which-key "Find File")
    "bb" '(ivy-switch-buffer :which-key "Find Buffer")
    "bd" '(kill-this-buffer :which-key "Kill Buffer")
    )

#+end_src

* UI Configuration

This section configures UI settings and defines the apparence of the Editor.

** Variables

Variables to adjust in each system

#+begin_src emacs-lisp

  (defvar owl/default-font-size 100)
  (defvar owl/default-variable-font-size 100)

  ;; Make frame transparency overridable
  (defvar owl/frame-transparency '(90 . 90))
  
#+end_src

** Basic Configuration

Remove ugly stuff and make Emacs look more minimal and modern

#+begin_src emacs-lisp

  (setq inhibit-startup-message t) ;;Disable startup message

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

  (menu-bar-mode -1)            ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell nil)

  (column-number-mode)
  (global-display-line-numbers-mode t)

  ;; Set frame transparency
  (set-frame-parameter (selected-frame) 'alpha owl/frame-transparency)
  (add-to-list 'default-frame-alist `(alpha . ,owl/frame-transparency))
  (set-frame-parameter (selected-frame) 'fullscreen 'maximized)
  (add-to-list 'default-frame-alist '(fullscreen . maximized))

  ;; Disable line numbers for some modes
  (dolist (mode '(org-mode-hook
                  term-mode-hook
                  shell-mode-hook
                  eshell-mode-hook))
    (add-hook mode (lambda () (display-line-numbers-mode 0))))

#+end_src

** Font Configuration

I like to use [[https://github.com/tonsky/FiraCode ][Fira Code]] and [[https://fonts.google.com/specimen/Cantarell][Cantarell]], bot fonts needs to be installed on machine

#+begin_src emacs-lisp

  (set-face-attribute 'default nil :font "Fira Code Retina" :height owl/default-font-size)

  (set-face-attribute 'fixed-pitch nil :font "Fira Code Retina" :height owl/default-font-size)

  (set-face-attribute 'variable-pitch nil :font "Cantarell" :height owl/default-variable-font-size :weight 'regular)

#+end_src

*** Debian

To install in Debian based OS we can run the following piece of code in terminal

#+begin_src shell :tangle no

  sudo apt install fonts-firacode fonts-cantarell -y

#+end_src

** Color Theme

[[https://github.com/doomemacs/themes][doom-themes]] is a set of themes used by [[https://github.com/doomemacs/doomemacs][Doom Emacs]]. We can run =M-x counsel-load-theme= to choose between them.

#+begin_src emacs-lisp

  (use-package doom-themes
    :init (load-theme 'doom-palenight t))

#+end_src

** Better Modeline

[[https://github.com/seagle0128/doom-modeline][doom-modeline]] is a attractive and rich mode line config for Emacs.

*NOTE:* The first time you load in new machine, you'll need to run =M-x all-the-icons-install-fonts= so that mode line icons display correctly

#+begin_src emacs-lisp

  (use-package all-the-icons)

  (use-package doom-modeline
    :ensure t
    :init (doom-modeline-mode 1)
    :custom ((doom-modeline-heigth 15)))

#+end_src

** Which Key

[[https://github.com/justbur/emacs-which-key][which-key]] is a useful panel that appears when you start to pressing any keybinding in Emacs and offer all possible completions fot the prefix.

#+begin_src emacs-lisp

  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))

#+end_src

** Ivy and Counsel

[[https://oremacs.com/swiper/][Ivy]] is an excellent completion framework for Emacs.  It provides a minimal yet powerful selection menu that appears when you open files, switch buffers, and for many other tasks in Emacs.  Counsel is a customized set of commands to replace =find-file= with =counsel-find-file=, etc which provide useful commands for each of the default completion commands.

[[https://github.com/Yevgnen/ivy-rich][ivy-rich]] adds extra columns to a few of the Counsel commands to provide more information about each item.

#+begin_src emacs-lisp

  (use-package ivy
    :diminish
    :bind (("C-s" . swiper)
           :map ivy-minibuffer-map
           ("TAB" . ivy-partial)
           ("C-l" . ivy-alt-done)
           ("C-j" . ivy-next-line)
           ("C-k" . ivy-previous-line)
           :map ivy-switch-buffer-map
           ("C-k" . ivy-previous-line)
           ("C-l" . ivy-done)
           ("C-d" . ivy-switch-buffer-kill)
           :map ivy-reverse-i-search-map
           ("C-k" . ivy-previous-line)
           ("C-d" . ivy-reverse-i-search-kill))
    :config
    (ivy-mode 1))

  (use-package ivy-rich
    :after ivy
    :init
    (ivy-rich-mode 1))

  (use-package counsel
    :bind (("C-M-j" . 'counsel-switch-buffer)
           :map minibuffer-local-map
           ("C-r" . 'counsel-minibuffer-history))
    :custom
    (counsel-linux-app-format-function #'counsel-linux-app-format-function-name-only)
    :config
    (counsel-mode 1))

#+end_src

*** Improve Candidate Sorting

[[https://github.com/radian-software/prescient.el][prescient.el]] provides some helpful behavior for sorting Ivy completion candidates. It can be especially helpful when using =M-x=

#+begin_src emacs-lisp

  (use-package ivy-prescient
    :after counsel
    :custom
    (ivy-prescient-enable-filtering nil)
    :config
    ;; Comment the following line to disable sorting remembered across sessions
    (prescient-persist-mode 1)

    (ivy-prescient-mode 1))

#+end_src

** Helpfull Help Commands

[[https://github.com/Wilfred/helpful][Helpful]] adds a lot of information to Emacs command buffers.

#+begin_src emacs-lisp

  (use-package helpful
    :commands (helpful-callable helpful-variable helpful-command helpful-key)
    :custom
    (counsel-describe-function-function #'helpful-callable)
    (counsel-describe-variable-function #'helpful-variable)
    :bind
    ([remap describe-function] . counsel-describe-function)
    ([remap describe-command] . helpful-command)
    ([remap describe-variable] . counsel-describe-variable)
    ([remap describe-key] . helpful-key))

#+end_src

** Text Scaling

Use of [[https://github.com/abo-abo/hydra][Hydra]] to quickly adjust scale of text on screen.

#+begin_src emacs-lisp

    (defhydra hydra-text-scale (:timeout 4)
      "scale text"
      ("j" text-scale-increase "in")
      ("k" text-scale-decrease "out")
      ("f" nil "finished" :exit t))

    (owl/leader-keys
      "ms" '(hydra-text-scale/body :which-key "scale text"))

#+end_src

* Productivity

This section configures all tools to improve productivity and help the daily things.

** Org Mode

[[https://orgmode.org/][Org Mode]] is one of the most awesome things in Emacs. It is a rich document editor, project planner, task and time tracker, blogging engine, and literate coding utility all wrapped up in one package.

*** Fonts and Bullets

Use bullets characters instead of asterisks.

#+begin_src emacs-lisp

  (defun owl/org-font-setup ()
    ;; Replace list hyphen with dot
    (font-lock-add-keywords 'org-mode
                            '(("^ *\\([-]\\) "
                               (0 (prog1 () (compose-region (match-beginning 1) (match-end 1) "•"))))))
    (dolist (face '((org-level-1 . 1.2)
                    (org-level-2 . 1.1)
                    (org-level-3 . 1.05)
                    (org-level-4 . 1.0)
                    (org-level-5 . 1.1)
                    (org-level-6 . 1.1)
                    (org-level-7 . 1.1)
                    (org-level-8 . 1.1)))
      (set-face-attribute (car face) nil :font "Cantarell" :weight 'regular :height (cdr face)))

    ;; Ensure that anything that should be fixed-pitch in Org files appears that way
    (set-face-attribute 'org-block nil :foreground nil :inherit 'fixed-pitch)
    (set-face-attribute 'org-code nil   :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-table nil   :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-verbatim nil :inherit '(shadow fixed-pitch))
    (set-face-attribute 'org-special-keyword nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-meta-line nil :inherit '(font-lock-comment-face fixed-pitch))
    (set-face-attribute 'org-checkbox nil :inherit 'fixed-pitch)

    ;; Get rid of the background on column views
    (set-face-attribute 'org-column nil :background nil)
    (set-face-attribute 'org-column-title nil :background nil))

#+end_src

*** Org Configuration

Set up Org Mode with a baseline configuration. The following sections will ad more things to it.

#+begin_src emacs-lisp

  (defun owl/org-mode-setup ()
    (org-indent-mode)
    (variable-pitch-mode 1)
    (visual-line-mode 1))

  (use-package org
    :pin org
    :commands (org-capture org-agenda)
    :hook (org-mode . owl/org-mode-setup)
    :config
    (setq org-ellipsis " ▾")

#+end_src

*** Workflow

This section contains the description and configuration of the productivity workflow I use with Org Mode.

**** Agenda files

#+begin_src emacs-lisp

  (setq org-agenda-files
        '("~/Workspaces/Personal/Agenda/Agenda.org"
          "~/Workspaces/Personal/Agenda/Dotfiles.org"))
  
#+end_src

**** Track Habits

#+begin_src emacs-lisp

  (require 'org-habit)
  (add-to-list 'org-modules 'org-habit)
  (setq org-habit-graph-column 60)

#+end_src

**** Todo keywords

#+begin_src emacs-lisp

  (setq org-todo-keywords
        '((sequence "TODO(t)" "NEXT(n)" "|" "DONE(d!)")
          (sequence "BACKLOG(b)" "PLAN(p)" "READY(r)" "ACTIVE(a)" "REVIEW(v)" "WAIT(w@/!)" "HOLD(h)" "|" "COMPLETED(c)" "CANC(k@)")))

#+end_src

**** Tags

#+begin_src emacs-lisp

  (setq org-tag-alist
        '((:startgroup)
          ;; Put mutually exclusive tags here
          (:endgroup)
          ("@errand" . ?E)
          ("@home" . ?H)
          ("@work" . ?W)
          ("agenda" . ?a)
          ("planning" . ?p)
          ("publish" . ?P)
          ("batch" . ?b)
          ("note" . ?n)
          ("idea" . ?i)))
  
#+end_src

**** Refiling

#+begin_src emacs-lisp

  ;; Set refile targets
  (setq org-refile-targets
        '(("Archive.org" :maxlevel . 1)
          ("Tasks.org" :maxlevel . 1)))

  ;; Save Org buffers after refiling!
  (advice-add 'org-refile :after 'org-save-all-org-buffers)
  
#+end_src

**** Custom Commands

#+begin_src emacs-lisp

  (setq org-agenda-custom-commands
        '(("d" "Dashboard"
           ((agenda "" ((org-deadline-warning-days 7)))
            (todo "NEXT"
                  ((org-agenda-overriding-header "Next Tasks")))
            (tags-todo "agenda/ACTIVE" ((org-agenda-overriding-header "Active Projects")))))

          ("n" "Next Tasks"
           ((todo "NEXT"
                  ((org-agenda-overriding-header "Next Tasks")))))

          ("W" "Work Tasks" tags-todo "+work-email")

          ;; Low-effort next actions
          ("e" tags-todo "+TODO=\"NEXT\"+Effort<15&+Effort>0"
           ((org-agenda-overriding-header "Low Effort Tasks")
            (org-agenda-max-todos 20)
            (org-agenda-files org-agenda-files)))

          ("w" "Workflow Status"
           ((todo "WAIT"
                  ((org-agenda-overriding-header "Waiting on External")
                   (org-agenda-files org-agenda-files)))
            (todo "REVIEW"
                  ((org-agenda-overriding-header "In Review")
                   (org-agenda-files org-agenda-files)))
            (todo "PLAN"
                  ((org-agenda-overriding-header "In Planning")
                   (org-agenda-todo-list-sublevels nil)
                   (org-agenda-files org-agenda-files)))
            (todo "BACKLOG"
                  ((org-agenda-overriding-header "Project Backlog")
                   (org-agenda-todo-list-sublevels nil)
                   (org-agenda-files org-agenda-files)))
            (todo "READY"
                  ((org-agenda-overriding-header "Ready for Work")
                   (org-agenda-files org-agenda-files)))
            (todo "ACTIVE"
                  ((org-agenda-overriding-header "Active Projects")
                   (org-agenda-files org-agenda-files)))
            (todo "COMPLETED"
                  ((org-agenda-overriding-header "Completed Projects")
                   (org-agenda-files org-agenda-files)))
            (todo "CANC"
                  ((org-agenda-overriding-header "Cancelled Projects")
                   (org-agenda-files org-agenda-files)))))))

#+end_src

**** Capture Templates

#+begin_src emacs-lisp

  (setq org-capture-templates
        `(("t" "Tasks / Projects")
          ("tt" "Task" entry (file+olp "~/Workspaces/Personal/Agenda/Tasks.org" "Inbox")
           "* TODO %?\n  %U\n  %a\n  %i" :empty-lines 1)

          ("j" "Journal Entries")
          ("jj" "Journal" entry
           (file+olp+datetree "~/Workspaces/Personal/Agenda/Journal.org")
           "\n* %<%I:%M %p> - Journal :journal:\n\n%?\n\n"
           ;; ,(dw/read-file-as-string "~/Notes/Templates/Daily.org")
           :clock-in :clock-resume
           :empty-lines 1)
          ("jm" "Meeting" entry
           (file+olp+datetree "~/Workspaces/Personal/Agenda/Journal.org")
           "* %<%I:%M %p> - %a :meetings:\n\n%?\n\n"
           :clock-in :clock-resume
           :empty-lines 1)

          ("w" "Workflows")
          ("we" "Checking Email" entry (file+olp+datetree "~/Workspaces/Personal/Agenda/Journal.org")
           "* Checking Email :email:\n\n%?" :clock-in :clock-resume :empty-lines 1)))

  (define-key global-map (kbd "C-c j")
    (lambda () (interactive) (org-capture nil "jj")))
  
#+end_src

*** End of =use-package org=

#+begin_src emacs-lisp

  (owl/org-font-setup))
  
#+end_src

*** Nicer Heading Bullets

[[https://github.com/sabof/org-bullets][org-bullets]] replaces the heading star in =org-mode=

#+begin_src emacs-lisp

  (use-package org-bullets
    :hook (org-mode . org-bullets-mode)
    :custom
    (org-bullets-bullet-list '("◉" "○" "●" "○" "●" "○" "●")))
  
#+end_src

*** Center Org Buffers

We use [[https://github.com/joostkremers/visual-fill-column][visual-fill-column]] to center =org-mode= buffers

#+begin_src emacs-lisp

  (defun owl/org-mode-visual-fill ()
    (setq visual-fill-column-width 100
          visual-fill-column-center-text t)
    (visual-fill-column-mode 1))

  (use-package visual-fill-column
    :hook (org-mode . owl/org-mode-visual-fill))
  
#+end_src

*** Babel

#+begin_src emacs-lisp

  (with-eval-after-load 'org
    (org-babel-do-load-languages
        'org-babel-load-languages
        '((emacs-lisp . t)
        (python . t))))
  
#+end_src

*** Automatic Tangle

#+begin_src emacs-lisp

  (defun owl/org-babel-tangle-config ()
    (when (string-equal (buffer-file-name)
                        (expand-file-name "~/Workspaces/Personal/dotfiles/Emacs/Emacs.org"))
      ;; Dynamic scoping to the rescue
      (let ((org-confirm-babel-evaluate nil))
        (org-babel-tangle))))

  (add-hook 'org-mode-hook (lambda () (add-hook 'after-save-hook #'owl/org-babel-tangle-config)))
#+end_src

*** Structure Templates

These templates enable you to type things like =<el= and then hit =Tab= to expand the template.

#+begin_src emacs-lisp
  
  ;; This is needed as of Org 9.2
  (require 'org-tempo)

  (add-to-list 'org-structure-template-alist '("sh" . "src sh"))
  (add-to-list 'org-structure-template-alist '("el" . "src emacs-lisp"))
  (add-to-list 'org-structure-template-alist '("li" . "src lisp"))
  (add-to-list 'org-structure-template-alist '("sc" . "src scheme"))
  (add-to-list 'org-structure-template-alist '("ts" . "src typescript"))
  (add-to-list 'org-structure-template-alist '("py" . "src python"))
  (add-to-list 'org-structure-template-alist '("go" . "src go"))
  (add-to-list 'org-structure-template-alist '("yaml" . "src yaml"))
  (add-to-list 'org-structure-template-alist '("json" . "src json"))

#+end_src

*** Searching

#+begin_src emacs-lisp

  (defun owl/search-org-files ()
    (interactive)
    (counsel-rg "" "~/Notes" nil "Search Notes: "))

#+end_src

*** Bindings

#+begin_src emacs-lisp

  (use-package evil-org
    :after org
    :hook ((org-mode . evil-org-mode)
           (org-agenda-mode . evil-org-mode)
           (evil-org-mode . (lambda () (evil-org-set-key-theme '(navigation todo insert textobjects additional)))))
    :config
    (require 'evil-org-agenda)
    (evil-org-agenda-set-keys))

  (owl/leader-keys
    "o"   '(:ignore t :which-key "org mode")

    "oi"  '(:ignore t :which-key "insert")
    "oil" '(org-insert-link :which-key "insert link")

    "on"  '(org-toggle-narrow-to-subtree :which-key "toggle narrow")

    "os"  '(owl/counsel-rg-org-files :which-key "search notes")

    "oa"  '(org-agenda :which-key "status")
    "ot"  '(org-todo-list :which-key "todos")
    "oc"  '(org-capture t :which-key "capture")
    "ox"  '(org-export-dispatch t :which-key "export"))

#+end_src

*** Auto-show Markup Symbols

This package makes it much easier to edit Org documents when =org-hide-emphasis-markers= is turned on.  It temporarily shows the emphasis markers around certain markup elements when you place your cursor inside of them.  No more fumbling around with ~=~ and ~*~ characters!

#+begin_src emacs-lisp

  (use-package org-appear
    :hook (org-mode . org-appear-mode))

#+end_src

* Applications

** Binding Prefix

#+begin_src emacs-lisp

  (owl/leader-keys
    "a"  '(:ignore t :which-key "apps"))

#+end_src

** RSS with Elfeed

[[https://github.com/skeeto/elfeed][Elfeed]] is a great RSS feed reader. Uses for keeping track a few blogs and subreddits. 

#+begin_src emacs-lisp

  (use-package elfeed
    :commands elfeed
    :config
    (setq elfeed-feeds
          '("https://nullprogram.com/feed/"
            "https://ambrevar.xyz/atom.xml"
            "https://guix.gnu.org/feeds/blog.atom"
            "https://valdyas.org/fading/feed/"
            "https://www.reddit.com/r/emacs/.rss")))

  (owl/leader-keys
    "ae" '(:ignore t :which-key "elfeed")
    "aee" '(elfeed :which-key "elfeed")
    "aeu" '(elfeed-update :which-key "elfeed-update")
    )

#+end_src

* Development

** Projectile

[[https://projectile.mx/][Projectile]] is a project management lib for Emacs.

#+begin_src emacs-lisp

  (use-package projectile
    :diminish projectile-mode
    :config (projectile-mode)
    :custom ((projectile-completion-system 'ivy))
    :bind-keymap
    ("C-c p" . projectile-command-map)
    :init
    ;; Set here the folder where we keep the Git Repos
    (when (file-directory-p "~/Workspaces")
      (setq projectile-project-search-path '("~/Workspaces")))
    (setq projectile-switch-project-action #'projectile-dired))

  (use-package counsel-projectile
    :after projectile
    :config (counsel-projectile-mode))

#+end_src

** Magit

[[https://magit.vc/][Magit]] is a git interface for Emacs. There's a aditional package for extend Magit and manage PR's and Issues. For configuring this we need to create a [[https://magit.vc/manual/forge/Token-Creation.html#Token-Creation][Github Token]]

#+begin_src emacs-lisp

  (use-package magit
    :commands magit-status
    :custom
    (magit-display-buffer-function #'magit-display-buffer-same-window-except-diff-v1))

  ;; Package for extend magit, uses for PRs ans Issues
  ;; Need configure GH Token first
  (use-package forge)

  (owl/leader-keys
    "g"   '(:ignore t :which-key "magit")

    "gg"  '(magit-status :which-key "magit-status"))

#+end_src

** Rainbow Delimiters

[[https://github.com/Fanael/rainbow-delimiters][rainbow-delimiters]] is usefull in prog-modes because it colorizes parantheses and brackets making a lot easier to visually match parentheses in lisp code without having to count them.

#+begin_src emacs-lisp

  (use-package rainbow-delimiters
    :hook (prog-mode . rainbow-delimiters-mode))

#+end_src

** Commenting

Emacs built in commenting functionality doesn't always works as expected, so we use [[https://github.com/redguardtoo/evil-nerd-commenter][evil-nerd-commenter]] to provide a more familiar behavior.

#+begin_src emacs-lisp

  (use-package evil-nerd-commenter
    :bind ("M-/" . evilnc-comment-or-uncomment-lines))
  
#+end_src

** LSP

We use [[https://emacs-lsp.github.io/lsp-mode/][lsp-mode]] to enable IDE-like functionality for many proggraming languages via "language servers".
The =lsp-keymap-prefix= setting enables you to define a prefix for where lsp-mode’s default keybindings will be added.
The =which-key= integration adds helpful descriptions of the various keys so you should be able to learn a lot just by pressing =C-c l= in a lsp-mode buffer

#+begin_src emacs-lisp

  (use-package lsp-mode
    :commands (lsp lsp-deferred)
    :hook (lsp-mode)
    :init
    (setq lsp-keymap-prefix "C-c l")  ;; Or 'C-l', 's-l'
    :config
    (lsp-enable-which-key-integration t))
  
#+end_src

*** LSP Ivy

[[https://github.com/emacs-lsp/lsp-ivy][lsp-ivy]] integrates Ivy with =lsp-mode= to make easy to search for things by name in our code.

#+begin_src emacs-lisp

  (use-package lsp-ivy
    :after lsp)

#+end_src

** Company Mode

[[https://company-mode.github.io/][Company Mode]] provides a nicer in-buffer completion interface.
We also use [[https://github.com/sebastiencs/company-box][company-box]] to furter enhance the look of completions with icons and better presentation

#+begin_src emacs-lisp

  (use-package company
    :after lsp-mode
    :hook (lsp-mode . company-mode)
    :bind (:map company-active-map
           ("<tab>" . company-complete-selection))
          (:map lsp-mode-map
           ("<tab>" . company-indent-or-complete-common))
    :custom
    (company-minimum-prefix-length 1)
    (company-idle-delay 0.0))

  (use-package company-box
    :hook (company-mode . company-box-mode))
  
#+end_src

* Languages

** Ruby

Basic configuration for Ruby Language

#+begin_src emacs-lisp

  (use-package ruby-mode
    :mode "\\.rb\\'"
    :hook (ruby-mode . lsp-deferred)
    :config
    (setq ruby-indent-level 2)
    (setq lsp-ruby-server-path "solargraph")
    (setq lsp-ruby-use-bundler t)
    (setq lsp-ruby-gem-args '("--document" "Solargraph::Pin=0" "--require" "solargraph")))
  
#+end_src

*** Server

#+begin_src shell tangle: no

  gem install solargraph

#+end_src

** Typescript

Basic configuration for Typescript language

#+begin_src emacs-lisp

  (use-package typescript-mode
    :mode "\\.ts\\'"
    :hook (typescript-mode . lsp-deferred)
    :config
    (setq typescript-indent-level 2))
  
#+end_src

*** Server

#+begin_src shell tangle: no

  npm install -g typescript-language-server typescript

#+end_src

* Terminal

Configure terminal

** Better term-mode colors

The =eterm-256color= package enhances the output of =term-mode=

#+begin_src emacs-lisp

  (use-package eterm-256color
    :hook (term-mode . eterm-256color-mode))
  
#+end_src

** vterm

[[https://github.com/akermu/emacs-libvterm/][vterm]] is a improved terminal emulator wich uses a copiled native module to interact with the undelying terminal applications.

#+begin_src emacs-lisp

  (use-package vterm
    :commands vterm
    :config
    (setq term-prompt-regexp "^[^#$%>\n]*[#$%>] *")  ;; Set this to match your custom shell prompt
    (setq vterm-shell "zsh")                         ;; Set this to customize the shell to launch
    (setq vterm-max-scrollback 10000))

#+end_src

** Keybidings

Using keybidings to easy launch terms

#+begin_src emacs-lisp

  (owl/leader-keys
    "t" '(:ignore t :which-key "terminal")

    "tv" '(vterm :which-key "vterm")
    "ta" '(ansi-term :which-key "ansi-term")
    "tt" '(term :which-key "term"))

#+end_src

* File Management

=Dired= is a built-in file manager for Emacs. Here's a Cheat Sheet to use it

** Dired

*** Key Bindings

**** Navigation

*Emacs* / *Evil*
- =n= / =j= - next line
- =p= / =k= - previous line
- =j= / =J= - jump to file in buffer
- =RET= - select file or directory
- =^= - go to parent directory
- =S-RET= / =g O= - Open file in "other" window
- =M-RET= - Show file in other window without focusing (previewing files)
- =g o= (=dired-view-file=) - Open file but in a "preview" mode, close with =q=
- =g= / =g r= Refresh the buffer with =revert-buffer= after changing configuration (and after filesystem changes!)

**** Marking files

- =m= - Marks a file
- =u= - Unmarks a file
- =U= - Unmarks all files in buffer
- =* t= / =t= - Inverts marked files in buffer
- =% m= - Mark files in buffer using regular expression
- =*= - Lots of other auto-marking functions
- =k= / =K= - "Kill" marked items (refresh buffer with =g= / =g r= to get them back)
- Many operations can be done on a single file if there are no active marks!

**** Copying and Renaming files

- =C= - Copy marked files (or if no files are marked, the current file)
- Copying single and multiple files
- =U= - Unmark all files in buffer
- =R= - Rename marked files, renaming multiple is a move!
- =% R= - Rename based on regular expression: =^test= , =old-\&=

*Power command*: =C-x C-q= (=dired-toggle-read-only=) - Makes all file names in the buffer editable directly to rename them!  Press =Z Z= to confirm renaming or =Z Q= to abort.

**** Deleting files

- =D= - Delete marked file
- =d= - Mark file for deletion
- =x= - Execute deletion for marks
- =delete-by-moving-to-trash= - Move to trash instead of deleting permanently

**** Creating and extracting archives

- =Z= - Compress or uncompress a file or folder to (=.tar.gz=)
- =c= - Compress selection to a specific file
- =dired-compress-files-alist= - Bind compression commands to file extension

**** Other common operations

- =T= - Touch (change timestamp)
- =M= - Change file mode
- =O= - Change file owner
- =G= - Change file group
- =S= - Create a symbolic link to this file
- =L= - Load an Emacs Lisp file into Emacs

*** Configuration

#+begin_src emacs-lisp
  
  (use-package dired
    :ensure nil
    :commands (dired dired-jump)
    :bind (("C-x C-j" . dired-jump))
    :custom ((dired-listing-switches "-agho --group-directories-first"))
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "h" 'dired-single-up-directory
      "l" 'dired-single-buffer))

  (use-package dired-single
    :commands (dired dired-jump))

  (use-package all-the-icons-dired
    :hook (dired-mode . all-the-icons-dired-mode))

  (use-package dired-open
    :commands (dired dired-jump)
    :config
    ;; Doesn't work as expected!
    ;;(add-to-list 'dired-open-functions #'dired-open-xdg t)
    (setq dired-open-extensions '(("png" . "feh")
                                  ("mkv" . "mpv"))))

  (use-package dired-hide-dotfiles
    :hook (dired-mode . dired-hide-dotfiles-mode)
    :config
    (evil-collection-define-key 'normal 'dired-mode-map
      "H" 'dired-hide-dotfiles-mode))

#+end_src

* Misc

** References

*** Resources

[[https://www.youtube.com/playlist?list=PLEoMzSkcN8oPH1au7H6B7bBJ4ZO7BXjSZ][Emacs From Scratch]] series. Without it this configuration will not exists.
[[https://github.com/emacs-tw/awesome-emacs][Awesome Emacs]] is a awesome list to packages and great stuffs

*** Dotfiles

[[https://github.com/daviwil/dotfiles/blob/9776d65c4486f2fa08ec60a06e86ecb6d2c40085/Emacs.org][David Wilson dotfiles]] - The real path to GNUrvana
