on: [workflow_dispatch]

jobs:
  build:
    uses: math-almeida/zmk/.github/workflows/build-user-config.yml@main
    with:
      build_matrix_path: Keyboard/corne/build.yml
      config_path: Keyboard/corne 
      root_config: Keyboard
